repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: build
        name: build script
        entry: bash -c "./build.sh"
        language: system
        types: [bash]
        pass_filenames: false
        always_run: true
        verbose: true

  - repo: local
    hooks:
      - id: linting
        name: golang-ci lint
        entry: bash -c "cd go && golangci-lint run --fast"
        language: system
        types: [bash]
        pass_filenames: false
        always_run: true
        verbose: true
