version: '3.9'

services:
  powerloom:
    build:
      context:
        ../
    expose:
      - 9000
      - 9002
    ports:
      - 9000:9000
      - 9002:9002

    depends_on:
      - "redis"
      - "rabbitmq"
    #  - "ipfs"

    links:
    #  - "ipfs"
      - "redis"
      - "rabbitmq"

    command:
      bash -c "docker/run_services.sh &&
      supervisord -n -c /etc/supervisord.conf -l log_test"

  pooler:
    image: powerloom-pooler
    depends_on:
      - "powerloom"
    expose:
      - 8002
    ports:
      - 8002:8002
    command:
      bash -c "sh init_processes.sh"
  redis:
    command: ["redis-server"]
    image: "redis"
    expose:
      - 6379
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    #command: ["daemon"]
    expose:
      - 15672
      - 5672
    ports:
      - 5672:5672
      - 15672:15672

  #ipfs:
  #  image: private-ipfs-node
  #  command: ["/usr/local/bin/start_ipfs"]
  #  expose:
  #    - 5001
  #  environment:
  #   - SWARM_KEY=8981939525395dc0ed49ffc8c9d2e91b6e23bb591ccc53762e8a4e83946d5f53
  #  ports:
  #    - 5001:5001



    
