version: '3.9'

services:
  powerloom:
    build:
      context:
        ../
    ports:
      - 9000:9000
      - 9002:9002

    depends_on:
      - "redis"
      - "rabbitmq"
      - "ipfs"

    links:
      - "ipfs"
      - "redis"
      - "rabbitmq"

    command:
      bash -c "docker/run_services.sh &&
      supervisord -n -c /etc/supervisord.conf -l log_test"

  redis:
    command: ["redis-server"]
    image: "redis"
    expose:
      - 6379
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq
    #command: ["daemon"]
    ports:
      - 5672:5672
      - 15672:15672

  ipfs:
    image: ipfs/go-ipfs:release
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    ports:
      - 5001:5001



    
