version: '3.9'

services:
  powerloom:
    build:
      context:
        ../
    ports:
      - 9000:9000
      - 9002:9002

    depends_on:
      - "redis"
      - "powergate"

    links:
      - "redis"
      - "powergate"

    command:
      bash -c "docker/run_services.sh &&
      supervisord -n -c /etc/supervisord.conf -l log_test"

  redis:
    command: ["redis-server"]
    image: "redis"
    expose:
      - 6379
    ports:
      - 6379:6379

  powergate:
    image: textile/powergate:latest
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
      - 7000:7000
    depends_on:
      - ipfs
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:v1.2.0
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=300
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
