powerloom:
	docker-compose -p powerloom up -V

powerloom-build:
	docker-compose -p powerloom up --build -V

powerloom-pg:
	docker-compose -p powerloom-pg -f docker-compose-powergate.yaml up -V

powerloom-pg-build:
	docker-compose -p powerloom-pg -f docker-compose-powergate.yaml up --build -V
