@startuml "Project's DAG Verification"
autonumber

participant "dag-verifier" as dagv
database redis
participant "IPFS-Node" as ipfs
participant "Slack-Notification-Endpoint" as slack

group periodic processing
    dagv <-> redis: Fetch lastVerificationState and lastIndexState for project
    note over dagv: VerificationState indicates the project's dag-height till which verification was done. \n IndexState indicates epoch till which project has been snapshotted.

    loop over all projects
        note over dagv: Fetch DAG Chain from lastVerifiedHeight to latest
        dagv <-> redis: Fetch dagChain from lastVerifiedHeight till latest from Cids ZSet
        dagv <-> redis: Fetch payloadCids from lastVerifiedHeight till latest from payloadCids ZSet
        note over dagv: Fix redis cache if it is corrupted.\n i.e in case of numOfPayloads != noOfDagBlocks
        loop over dagChain
            note over dagv: Fetch payloadData from local-file-cache using payloadCid
            alt if not present in file-cache
                dagv <-> ipfs: Fetch payload from ipfs using cat
            end
        end
        group verify dagChain for issues
            note over dagv: Go through each dag-payload decoded partially (only ChainHeightRange).\n Identify if there is a gap or duplicate.
            alt if payload is null
                note over dagv: Record it as dagChainGap.
            end
        end
        alt if dagChain has issues
            dagv <-> redis: Record dagChainIssues in project specific Zset {projectId}:dagChainGaps
        end

    end

    loop over projects
        dagv <-> redis: Get project currentFinalizedHeight
        alt if lastVerifiedHeight == currentFinalizedHeight
            note over dagv: projectStuckCycleCount++
            alt if projectStuckCycleCount > 3
                note over dagv: Record as summaryProjectStuck/project
            end
        else
            alt if prevCycleSummaryProjectstuck
                note over dagv: Record as summaryProjectMovingAhead
            end
        end
    end

    alt if projects have dagChainIssues or summaryProjectStuck
            dagv <-> slack: Report projects having dagIssues or number of projects stuck along with summaryProjects
    else
        alt if summaryProjectMovingAhead
            dagv <-> slack: Report a cleared alrt indicating summaryProject is moving ahead.
        end
    end

    dagv <-> redis: Update verification and Index State for the project.
end