@startuml "Token Aggregation"
autonumber

participant "token-aggregator" as tokenagg
database redis
participant "audit-protocol-backend" as apb


group init

    tokenagg <-> apb: Register for blockHeightConfirmCallback for all summaryProjects

end


group periodic processing

    tokenagg <-> apb: Fetch finalizedHeight for PairSummary project (pairSummary.finalizedHeight)

    alt if lastFinalizedHeight > pairSummary.finalizedHeight
        tokenagg <-> redis: Fetch metadata for all tokens uniswap:pairContract:{tokenContractAddress}:PairContractTokensData
        tokenagg <-> redis : Fetch cached pairsummary snapshot based on finalizedHeight

        loop over tokenPairData
            note over tokenagg: Aggregate all data from SummarySnapshot based on tokenContractAddress
        end

        note over tokenagg: Record blockTimeStamp from pairsummarySnapshot

        loop over tokens
            tokenagg <-> redis: Fetch tokenPrice in USD at blockHeight. This info is cached by pooler in redis.
            note over tokenagg: TODO: rather than using information cached by pooler, this should be part of pair-reserves snapshot.
            tokenagg <-redis: Update TokenPriceHistory Zset (timestamp <-> tokenPrice) with latestPrice and blockTimestamp(from pairSummarySnapshot)

            note over tokenagg: Arrive at 24hour priceChange by using curBlockTimestamp and 24hour old timestamp and TokenPriceHistory Zset.
        end

        tokenagg <-> apb: Commit snapshot for TokenSummary

        tokenagg <-> redis: Fetch finalized tokenSummary Snapshot blockHeight (tokenSummary.finalizedHeight)
        note over tokenagg: set tentativeHeight as tokenSummary.finalizedHeight+1
        note over tokenagg: poll for status of tentativeHeight
        alt if tentativeHeight.Status > TX_CONFIRMATION_PENDING
            tokenagg <-> redis: Cache snapshot in redis and add it to zset to be served via core-api.
        end

        loop over tokens
            tokenagg <-> redis : Prune tokenPrice Zset for entries older than 24hours
        end
    end
end
